#include<iostream>
#include<conio.h>
#include<fstream>

using namespace std;

class contact
{
private:

   char fName[50],lName[50],address[50],email[50];
   long long phNo;

public:
    void createContact()
    {
        cout<<"Enter the first Name:";
        cin>>fName;

        cout<<"Enter the lName:";
        cin>>lName;

        cout<<"Enter Phone Number:";
        cin>>phNo;

        cout<<"Enter Address:";
        cin>>address;

        cout<<"Enter Email ID:";
        cin>>email;


    }

    void showContact()
    {

        cout<<"Name:"<<fName<<" "<<lName<<endl;
        cout<<"Phone : "<<phNo<<endl;
        cout<<"Address:"<<address<<endl;
        cout<<"Email:"<<email<<endl;;
    }

    void writeOnFile()
    {
        char ch;
        ofstream f1;
        f1.open("CMS.dat",ios::binary | ios::app); /* ios::binary-- " make sure the data is read or written without translating new line character to & from \r\n on the fly"
                                                      ios::app--"set the stream's position indicator to the end of the stream before each output operation"*/

      do{

       createContact();
       f1.write(reinterpret_cast<char*>(this),sizeof(*this));
       cout<<"Do you have next data?(y/n)";
       cin>>ch;

       } while(ch=='y');

       cout<<"Contact has been Successfully Created... ";
       f1.close();

    }
    void readFromFile()
    {
        ifstream f2;
        f2.open("CMS.dat", ios::binary);  //does not need reading the file


        cout<<"\n======================================================================\n";
        cout<<"LIST OF CONTACTS";
        cout<<"\n======================================================================\n";

        while(!f2.eof()) { /*Use EOF to avoid the error generated by attempting to get input past the end of a file.
                                     The EOF function returns False until the end of the file has been reached
                                     The eof() method of ios class in C++ is used to check if the stream is has raised any EOF (End Of File) error. */


                       if(f2.read(reinterpret_cast<char*>(this),sizeof(*this)))
                          {
                              showContact();
                               cout<<"\n======================================================================\n";

                          }

        }
        f2.close();
    }
    void searchOnFile()
      {
        ifstream f3;
        long long phone;
        cout<<"Enter Phone No.";
        cin>>phone;
        f3.open("CMS.dat", ios::binary);

        while(!f3.eof()){
                if(f3.read(reinterpret_cast<char*>(this),sizeof(*this)))
              {
                  if(phone==phNo)
                  {



                    showContact();
                    return;
              }

        }
    }
    cout<<"\n\nNo record found";
    f3.close();
}

  void deleteFromFile()
  {
      long long num;
      int flag = 0;
      ofstream f4;
      ifstream f5;

      f5.open("CMS.dat",ios::binary);
      f4.open("temp.dat",ios::binary);

      cout<<"Enter phone no. to delete::";
      cin>>num;

      while(!f5.eof())/*-----/*Use EOF to avoid the error generated by attempting to get input past the end of a file.
                                     The EOF function returns False until the end of the file has been reached
                                     The eof() method of ios class in C++ is used to check if the stream is has raised any EOF (End Of File) error. */
      {
          if(f5.read(reinterpret_cast<char*>(this),sizeof(*this)))

      {
      if(phNo != num){
                f4.write(reinterpret_cast<char*>(this),sizeof(*this));
            }else
            flag =1;
      }
  }
  f5.close();
  f4.close();
  remove("CMS.dat");
  rename ("temp.dat","CMS.dat");

  flag==1 ?
  cout<<"\tContact Deleted....":
  cout<<"\tContact Not Found....";

  }
  void editContact()
  {
      long long num;
      fstream f6;

      cout<<"Edit Contact";
      cout<<"\n======================================================================\n";
      cout<<"Enter the phone number to be edit: ";
      cin>>num;

      f6.open("CMA.dat", ios::binary|ios::out|ios::in);


      while(!f6.eof())
      {
          if(f6.read(reinterpret_cast<char*>(this),sizeof(*this)))
          {
              if(phNo==num){
                cout<<"Enter new records\n";
                createContact();


                int pos = -1*sizeof(*this);
                f6.seekp(pos,ios::cur);
                f6.write(reinterpret_cast<char*>(this),sizeof(*this));
                cout<<endl<<endl<<"\tContact Successfully Updated...";
                return;
              }
          }
      }
      cout<<"\n\nNo Records found";
      f6.close();
  }
  };

  int main()
  {
      system("cls"); //cls- means clearscreen
      system("Color 3F"); //Color XY,X=Background colour,Y=Text color

      cout<<"\n\n\n\n\n\n\n\n\n\n\t\t* Welcome TO THE CONTACT MANAGEMENT SYSTEM*";
      getch();


      while(1)
      {
          contact c1;
          int choice;

          system("cls");
          system("Color 03");


          cout<<"\nCONTACT MANAGEMENT SYSTEM";
          cout<<"\n\nMAIN MENU";
          cout<<"\n======================================================================\n";
          cout<<"[1] Add a new Contact\n";
          cout<<"[2] List all contacts\n";
          cout<<"[3] Search for Contact\n";
          cout<<"[4] Delete a Contact\n";
          cout<<"[5] Edit a Contact\n";
          cout<<"[0] Exit";
          cout<<"\n======================================================================\n";
          cout<<"Enter your choice:";
          cin>>choice;



          switch(choice)
          {
          case 1:
            system("cls");
            c1.writeOnFile();
            break;

          case 2:
            system("cls");
            c1.readFromFile();


          case 3:
            system("cls");
            c1.searchOnFile();
            break;


          case 4:
            system("cls");
            c1.deleteFromFile();
            break;

          case 5:
            system("cls");
            c1.editContact();
            break;

          case 0:
            system("cls");
            cout<<"\n\n\n\t\t\tThank You for using CMS."<<endl<<endl;
            exit(0);
            break;


          default:

            continue;

          }

          int opt;
          cout<<"\n\n...::Enter the choice:\n[1] Main Menu\t\t[0] Exit\n";
          cin>>opt;


          switch(opt)
          {
            case 0:
            system("cls");
            cout<<"\n\n\n\t\t\tThank You for using CMS."<<endl<<endl;
            exit(0);
            break;

            default:
                continue;



          }

     }

     return 0;
  }








